AWSTemplateFormatVersion: 2010-09-09
Description: A simple CloudFormation template
Resources:
    MyBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: my-cloudformation-demo
Outputs:
  BucketARN:
    Description: The ARN of the bucket
    Value: !GetAtt MyBucket.Arn
