AWSTemplateFormatVersion: 2010-09-09
Description: A simple CloudFormation template
Parameters:
  BucketName:
    Description: | 
      Provide a bucket name to hold packaged resources
    Type: String  
Resources:
    Bucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Ref BucketName
            