---
AWSTemplateFormatVersion: '2010-09-09'
Description: A test stack for demonstrating Cloudformation
Parameters:
  Subnet:
    Description: Subnet in which to place the resources
    Type: AWS::EC2::Subnet::Id
    # this type is not that helpful, since it just shows IDs
  InstanceType:
    Description: The instance type for the Launch Config
    Type: String
    Default: t2.micro
    AllowedValues:
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
  AMI:
    Description: a reference to the AMI you want
    Type: AWS::EC2::Image::Id
    Default: ami-0b0dcb5067f052a63
  InstanceName:
    Description: The Name tag that will get applied to the instance
    Type: String
    Default: NginxDemo
Resources:
  SecurityGroupHTTPFromWorld:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows port 80 from the world
      GroupName: HTTPFromWorld
      # If we do not specify egress, the default 
      # "all traffic" egress rule will be created.
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      # Do I need VPC ID?
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      UserData:
        Fn::Base64: |
          #!/bin/bash -xe
          sudo amazon-linux-extras install -y nginx1
          sudo service nginx start
      ImageId: !Ref AMI
      InstanceType:
        Ref: InstanceType
      SecurityGroupIds:
        - !GetAtt SecurityGroupHTTPFromWorld.GroupId
      SubnetId:
        Ref: Subnet
      Tags:
        - Key: Name
          Value: !Ref InstanceName          