Description: >
    Simple custom resource demo
Resources:

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: Allows Cloudformation to call services on your behalf.  Slight change.
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      RoleName: CloudformationServiceRole

  MyCustomResourceFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
              var response = require('cfn-response');
              var aws = require("aws-sdk");

              exports.handler = function(event, context) {
                
                  var responseText = "starting function"
                  var s3 = new aws.S3();
                  var bucketName = event.ResourceProperties.BucketName;
                  responseText = "got bucket name: " + bucketName

                  if ( event.RequestType == 'Create' ) {

                      s3.createBucket( { Bucket: bucketName }, function(err,data) {
                          responseText = "created bucket " + bucketName
                      })
                      
                  } else if ( event.RequestType  == 'Delete' ) {

                      s3.deleteBucket({Bucket: bucketName}, function(err,data){
                          responseText = "deleted bucket " + bucketName
                      })

                  }

                  var responseData = {msg: "hello world!", responseText: responseText};
                  response.send(event, context, response.SUCCESS, responseData);

              };        
      Handler: index.handler
      Timeout: 30
      Runtime: nodejs14.x
      Role: !GetAtt LambdaExecutionRole.Arn 

Outputs:
  MyCustomResourceArn:
    Description: The ARN of the custom resource, exported for use by others
    Value: !GetAtt MyCustomResourceFunction.Arn
    Export: 
      Name: MyCustomResourceArn
    