---
AWSTemplateFormatVersion: '2010-09-09'
Description: A test stack for demonstrating Cloudformation
Parameters:
  Subnet:
    Description: Subnet in which to place the resources
    Type: AWS::EC2::Subnet::Id
  InstanceType:
    Description: The instance type for the Launch Config
    Type: String
    Default: t2.micro
    AllowedValues:
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo amazon-linux-extras install -y nginx1
          sudo service nginx start
          /opt/aws/bin/cfn-signal -exit-code 0 --stack ${AWS::StackName} --resource MyInstance --region ${AWS::Region}  
    CreationPolicy:  # note the nesting.  CreationPolicy is not under Properties, but a direct child of the resource.
      ResourceSignal:
        Timeout: PT15M
        Count: 5
      ImageId: ami-087c17d1fe0178315
      InstanceType:
        Ref: InstanceType
      SubnetId:
        Ref: Subnet        