---
AWSTemplateFormatVersion: '2010-09-09'
Description: |
  A template that creates a macro definition based on the pre-existing lambda ARN.
Parameters:
  FunctionARN:
    Description: ARN of the macro lambda function
    Type: String
Resources:
  Macro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: MyNoChangeMacro
      Description: Definition for the macro
      FunctionName: !Ref FunctionARN