---
AWSTemplateFormatVersion: 2010-09-09
Description: |
  A template that demonstrates how to use a macro at both 
  template and snippet levels with parameters.
Parameters:
  BucketName:
    Type: String
Transform:
  - Name: MyNoChangeMacro
    Parameters:
      Hello: World
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      'Fn::Transform':   # cfn lint incorrectly flags this
        Name: 'MyNoChangeMacro'
        Parameters:
          Foo: Bar